// Package globacl provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package globacl

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for Action.
const (
	ActionAllowOverride Action = "allow_override"
	ActionDelete        Action = "delete"
	ActionDeny          Action = "deny"
)

// Defines values for AllowDecisionDecision.
const (
	Allow AllowDecisionDecision = "allow"
)

// Defines values for CanaryStatusResponseStatus.
const (
	CanaryStatusResponseStatusOk CanaryStatusResponseStatus = "ok"
)

// Defines values for DeliveryPriorityValue.
const (
	DeliveryPriorityValueP0 DeliveryPriorityValue = "p0"
	DeliveryPriorityValueP1 DeliveryPriorityValue = "p1"
	DeliveryPriorityValueP2 DeliveryPriorityValue = "p2"
)

// Defines values for DenyDecisionDecision.
const (
	DenyDecisionDecisionDeny DenyDecisionDecision = "deny"
)

// Defines values for HealthResponseRole.
const (
	Agent     HealthResponseRole = "agent"
	Candidate HealthResponseRole = "candidate"
	Control   HealthResponseRole = "control"
	Follower  HealthResponseRole = "follower"
	Leader    HealthResponseRole = "leader"
	Relay     HealthResponseRole = "relay"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
	HealthResponseStatusStale    HealthResponseStatus = "stale"
)

// Defines values for HistoryCompactedResponseReason.
const (
	HistoryCompactedResponseReasonHistoryCompacted HistoryCompactedResponseReason = "history_compacted"
)

// Defines values for HistoryCompactedResponseStatus.
const (
	Compacted HistoryCompactedResponseStatus = "compacted"
)

// Defines values for NoCanaryStatusStatus.
const (
	None NoCanaryStatusStatus = "none"
)

// Defines values for PropagationStatusResponseStatus.
const (
	PropagationStatusResponseStatusDegraded PropagationStatusResponseStatus = "degraded"
	PropagationStatusResponseStatusOk       PropagationStatusResponseStatus = "ok"
)

// Defines values for RollbackResponseStatus.
const (
	RollbackResponseStatusOk RollbackResponseStatus = "ok"
)

// Defines values for RuleKind.
const (
	DomainSuffix RuleKind = "domain_suffix"
	Ipv4Cidr     RuleKind = "ipv4_cidr"
)

// Defines values for SignatureEnvelopeAlgorithm.
const (
	Ed25519 SignatureEnvelopeAlgorithm = "ed25519"
)

// Defines values for DeliveryPriority.
const (
	DeliveryPriorityP0 DeliveryPriority = "p0"
	DeliveryPriorityP1 DeliveryPriority = "p1"
	DeliveryPriorityP2 DeliveryPriority = "p2"
)

// Defines values for GetMutationsParamsDeliveryPriority.
const (
	GetMutationsParamsDeliveryPriorityP0 GetMutationsParamsDeliveryPriority = "p0"
	GetMutationsParamsDeliveryPriorityP1 GetMutationsParamsDeliveryPriority = "p1"
	GetMutationsParamsDeliveryPriorityP2 GetMutationsParamsDeliveryPriority = "p2"
)

// Defines values for GetMutationsSignatureParamsDeliveryPriority.
const (
	GetMutationsSignatureParamsDeliveryPriorityP0 GetMutationsSignatureParamsDeliveryPriority = "p0"
	GetMutationsSignatureParamsDeliveryPriorityP1 GetMutationsSignatureParamsDeliveryPriority = "p1"
	GetMutationsSignatureParamsDeliveryPriorityP2 GetMutationsSignatureParamsDeliveryPriority = "p2"
)

// AckRequest defines model for AckRequest.
type AckRequest struct {
	union json.RawMessage
}

// Action defines model for Action.
type Action string

// AllowDecision defines model for AllowDecision.
type AllowDecision struct {
	Decision AllowDecisionDecision `json:"decision"`
}

// AllowDecisionDecision defines model for AllowDecision.Decision.
type AllowDecisionDecision string

// AuditLogEntry defines model for AuditLogEntry.
type AuditLogEntry struct {
	Duplicate *bool   `json:"duplicate,omitempty"`
	Event     string  `json:"event"`
	Key       *string `json:"key,omitempty"`
	Kind      *string `json:"kind,omitempty"`
	Mutations *int64  `json:"mutations,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	OpId      *string `json:"op_id,omitempty"`
	Pattern   *string `json:"pattern,omitempty"`
	Reason    *string `json:"reason,omitempty"`
	Result    string  `json:"result"`

	// Seq Monotonic per-shard sequence number.
	Seq      *Sequence `json:"seq,omitempty"`
	ShardId  *ShardId  `json:"shard_id,omitempty"`
	Snapshot *string   `json:"snapshot,omitempty"`

	// Ts Unix timestamp in seconds.
	Ts                   UnixTimestamp                                 `json:"ts"`
	AdditionalProperties map[string]AuditLogEntry_AdditionalProperties `json:"-"`
}

// AuditLogEntry0 defines model for .
type AuditLogEntry0 = string

// AuditLogEntry1 defines model for .
type AuditLogEntry1 = int

// AuditLogEntry2 defines model for .
type AuditLogEntry2 = bool

// AuditLogEntry_AdditionalProperties defines model for AuditLogEntry.AdditionalProperties.
type AuditLogEntry_AdditionalProperties struct {
	union json.RawMessage
}

// AuditLogResponse defines model for AuditLogResponse.
type AuditLogResponse struct {
	Items *[]AuditLogEntry `json:"items,omitempty"`
}

// BinaryPayload defines model for BinaryPayload.
type BinaryPayload = openapi_types.File

// CanaryStatusResponse defines model for CanaryStatusResponse.
type CanaryStatusResponse struct {
	// CreatedAtUnix Unix timestamp in seconds.
	CreatedAtUnix    UnixTimestamp         `json:"created_at_unix"`
	DeliveryPriority DeliveryPriorityValue `json:"delivery_priority"`

	// ExpiresAt Unix timestamp in seconds.
	ExpiresAt UnixTimestamp `json:"expires_at"`
	Key       string        `json:"key"`
	Namespace string        `json:"namespace"`
	OpId      string        `json:"op_id"`

	// Seq Monotonic per-shard sequence number.
	Seq      Sequence                   `json:"seq"`
	ShardId  ShardId                    `json:"shard_id"`
	Status   CanaryStatusResponseStatus `json:"status"`
	TenantId string                     `json:"tenant_id"`
}

// CanaryStatusResponseStatus defines model for CanaryStatusResponse.Status.
type CanaryStatusResponseStatus string

// CommitOutcomeResponse defines model for CommitOutcomeResponse.
type CommitOutcomeResponse struct {
	Action Action `json:"action"`

	// CommittedAtUnix Unix timestamp in seconds.
	CommittedAtUnix  UnixTimestamp         `json:"committed_at_unix"`
	DeliveryPriority DeliveryPriorityValue `json:"delivery_priority"`
	Duplicate        bool                  `json:"duplicate"`
	EntriesChanged   int32                 `json:"entries_changed"`

	// Epoch Monotonic per-shard sequence number.
	Epoch    Sequence  `json:"epoch"`
	KeyHash  uint64    `json:"key_hash"`
	Pattern  *string   `json:"pattern,omitempty"`
	RuleHash *uint64   `json:"rule_hash,omitempty"`
	RuleKind *RuleKind `json:"rule_kind,omitempty"`

	// Seq Monotonic per-shard sequence number.
	Seq     Sequence `json:"seq"`
	ShardId ShardId  `json:"shard_id"`
}

// DecisionResponse defines model for DecisionResponse.
type DecisionResponse struct {
	union json.RawMessage
}

// DeliveryPriorityValue defines model for DeliveryPriorityValue.
type DeliveryPriorityValue string

// DenyDecision defines model for DenyDecision.
type DenyDecision struct {
	Decision DenyDecisionDecision `json:"decision"`

	// Epoch Monotonic per-shard sequence number.
	Epoch      Sequence `json:"epoch"`
	Priority   int32    `json:"priority"`
	ReasonCode string   `json:"reason_code"`

	// Seq Monotonic per-shard sequence number.
	Seq     Sequence `json:"seq"`
	ShardId ShardId  `json:"shard_id"`
}

// DenyDecisionDecision defines model for DenyDecision.Decision.
type DenyDecisionDecision string

// DenyMutationRequest defines model for DenyMutationRequest.
type DenyMutationRequest struct {
	Action              Action                 `json:"action"`
	BlastRadiusOverride *bool                  `json:"blast_radius_override,omitempty"`
	CreatedBy           *string                `json:"created_by,omitempty"`
	DeliveryPriority    *DeliveryPriorityValue `json:"delivery_priority,omitempty"`

	// ExpiresAt Unix timestamp in seconds.
	ExpiresAt           *UnixTimestamp `json:"expires_at,omitempty"`
	Key                 string         `json:"key"`
	Namespace           string         `json:"namespace"`
	OpId                string         `json:"op_id"`
	OverrideBlastRadius *bool          `json:"override_blast_radius,omitempty"`
	Priority            *int32         `json:"priority,omitempty"`
	ReasonCode          *string        `json:"reason_code,omitempty"`
	TenantId            string         `json:"tenant_id"`
	TwoPersonApproved   *bool          `json:"two_person_approved,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Reason string `json:"reason"`
	Status string `json:"status"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Role                 *HealthResponseRole                            `json:"role,omitempty"`
	Status               HealthResponseStatus                           `json:"status"`
	AdditionalProperties map[string]HealthResponse_AdditionalProperties `json:"-"`
}

// HealthResponse0 defines model for .
type HealthResponse0 = string

// HealthResponse1 defines model for .
type HealthResponse1 = int

// HealthResponse2 defines model for .
type HealthResponse2 = bool

// HealthResponse_AdditionalProperties defines model for HealthResponse.AdditionalProperties.
type HealthResponse_AdditionalProperties struct {
	union json.RawMessage
}

// HealthResponseRole defines model for HealthResponse.Role.
type HealthResponseRole string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HistoryCompactedResponse defines model for HistoryCompactedResponse.
type HistoryCompactedResponse struct {
	// CompactedSeq Monotonic per-shard sequence number.
	CompactedSeq Sequence                       `json:"compacted_seq"`
	Reason       HistoryCompactedResponseReason `json:"reason"`
	Status       HistoryCompactedResponseStatus `json:"status"`
}

// HistoryCompactedResponseReason defines model for HistoryCompactedResponse.Reason.
type HistoryCompactedResponseReason string

// HistoryCompactedResponseStatus defines model for HistoryCompactedResponse.Status.
type HistoryCompactedResponseStatus string

// LatestCanaryResponse defines model for LatestCanaryResponse.
type LatestCanaryResponse struct {
	union json.RawMessage
}

// NoCanaryStatus defines model for NoCanaryStatus.
type NoCanaryStatus struct {
	Status NoCanaryStatusStatus `json:"status"`
}

// NoCanaryStatusStatus defines model for NoCanaryStatus.Status.
type NoCanaryStatusStatus string

// PopAckRequest defines model for PopAckRequest.
type PopAckRequest struct {
	AgentId string `json:"agent_id"`

	// AppliedAtUnix Unix timestamp in seconds.
	AppliedAtUnix *UnixTimestamp `json:"applied_at_unix,omitempty"`
	Entries       *int64         `json:"entries,omitempty"`

	// Seq Monotonic per-shard sequence number.
	Seq     Sequence `json:"seq"`
	ShardId ShardId  `json:"shard_id"`
}

// PropagationAckRequest defines model for PropagationAckRequest.
type PropagationAckRequest struct {
	AgentId string `json:"agent_id"`

	// AppliedAtUnix Unix timestamp in seconds.
	AppliedAtUnix *UnixTimestamp `json:"applied_at_unix,omitempty"`
	Entries       *int64         `json:"entries,omitempty"`
	Location      string         `json:"location"`
	RelayId       string         `json:"relay_id"`

	// RelayReceivedAtUnix Unix timestamp in seconds.
	RelayReceivedAtUnix *UnixTimestamp `json:"relay_received_at_unix,omitempty"`

	// Seq Monotonic per-shard sequence number.
	Seq     Sequence `json:"seq"`
	ShardId ShardId  `json:"shard_id"`
}

// PropagationAckStatus defines model for PropagationAckStatus.
type PropagationAckStatus struct {
	AckAgeSecs *int64 `json:"ack_age_secs,omitempty"`
	AgentId    string `json:"agent_id"`

	// AppliedAtUnix Unix timestamp in seconds.
	AppliedAtUnix UnixTimestamp `json:"applied_at_unix"`
	Entries       int64         `json:"entries"`
	LagSecs       *int64        `json:"lag_secs,omitempty"`
	Location      string        `json:"location"`
	RelayId       string        `json:"relay_id"`

	// RelayReceivedAtUnix Unix timestamp in seconds.
	RelayReceivedAtUnix UnixTimestamp `json:"relay_received_at_unix"`

	// Seq Monotonic per-shard sequence number.
	Seq Sequence `json:"seq"`

	// SeqLag Monotonic per-shard sequence number.
	SeqLag  *Sequence `json:"seq_lag,omitempty"`
	ShardId ShardId   `json:"shard_id"`

	// SourceSeq Monotonic per-shard sequence number.
	SourceSeq *Sequence `json:"source_seq,omitempty"`
}

// PropagationStatusResponse defines model for PropagationStatusResponse.
type PropagationStatusResponse struct {
	AckCount        int64                   `json:"ack_count"`
	AckedShards     int64                   `json:"acked_shards"`
	Acks            *[]PropagationAckStatus `json:"acks,omitempty"`
	AgentCount      int64                   `json:"agent_count"`
	LaggingAckCount int64                   `json:"lagging_ack_count"`
	MaxAckAgeSecs   int64                   `json:"max_ack_age_secs"`

	// MaxAckSeq Monotonic per-shard sequence number.
	MaxAckSeq Sequence `json:"max_ack_seq"`

	// MaxSeqLag Monotonic per-shard sequence number.
	MaxSeqLag Sequence `json:"max_seq_lag"`

	// MinAckSeq Monotonic per-shard sequence number.
	MinAckSeq  Sequence `json:"min_ack_seq"`
	RelayCount int64    `json:"relay_count"`
	ShardCount int32    `json:"shard_count"`

	// SourceMaxSeq Monotonic per-shard sequence number.
	SourceMaxSeq Sequence                        `json:"source_max_seq"`
	Status       PropagationStatusResponseStatus `json:"status"`
}

// PropagationStatusResponseStatus defines model for PropagationStatusResponse.Status.
type PropagationStatusResponseStatus string

// RelayAcksResponse defines model for RelayAcksResponse.
type RelayAcksResponse struct {
	AckCount int64                   `json:"ack_count"`
	Acks     *[]PropagationAckStatus `json:"acks,omitempty"`
	Location string                  `json:"location"`
	RelayId  string                  `json:"relay_id"`
}

// RollbackRequest defines model for RollbackRequest.
type RollbackRequest struct {
	Snapshot string `json:"snapshot"`
}

// RollbackResponse defines model for RollbackResponse.
type RollbackResponse struct {
	Mutations int64                  `json:"mutations"`
	Snapshot  string                 `json:"snapshot"`
	Status    RollbackResponseStatus `json:"status"`
}

// RollbackResponseStatus defines model for RollbackResponse.Status.
type RollbackResponseStatus string

// RuleKind defines model for RuleKind.
type RuleKind string

// RuleMutationRequest defines model for RuleMutationRequest.
type RuleMutationRequest struct {
	Action              Action                 `json:"action"`
	BlastRadiusOverride *bool                  `json:"blast_radius_override,omitempty"`
	CreatedBy           *string                `json:"created_by,omitempty"`
	DeliveryPriority    *DeliveryPriorityValue `json:"delivery_priority,omitempty"`

	// ExpiresAt Unix timestamp in seconds.
	ExpiresAt           *UnixTimestamp `json:"expires_at,omitempty"`
	Kind                RuleKind       `json:"kind"`
	OpId                string         `json:"op_id"`
	OverrideBlastRadius *bool          `json:"override_blast_radius,omitempty"`
	Pattern             string         `json:"pattern"`
	Priority            *int32         `json:"priority,omitempty"`
	ReasonCode          *string        `json:"reason_code,omitempty"`
	TenantId            string         `json:"tenant_id"`
	TwoPersonApproved   *bool          `json:"two_person_approved,omitempty"`
}

// Sequence Monotonic per-shard sequence number.
type Sequence = int64

// ShardId defines model for ShardId.
type ShardId = int32

// SignatureEnvelope defines model for SignatureEnvelope.
type SignatureEnvelope struct {
	Algorithm SignatureEnvelopeAlgorithm `json:"algorithm"`
	KeyId     string                     `json:"key_id"`

	// KeyVersion Monotonic per-shard sequence number.
	KeyVersion Sequence `json:"key_version"`
	Signature  string   `json:"signature"`
}

// SignatureEnvelopeAlgorithm defines model for SignatureEnvelope.Algorithm.
type SignatureEnvelopeAlgorithm string

// SnapshotListResponse defines model for SnapshotListResponse.
type SnapshotListResponse struct {
	Manifest      *SnapshotNameOrList `json:"manifest,omitempty"`
	ManifestCount int64               `json:"manifest_count"`
	Snapshot      *SnapshotNameOrList `json:"snapshot,omitempty"`
	SnapshotCount int64               `json:"snapshot_count"`
}

// SnapshotManifestResponse defines model for SnapshotManifestResponse.
type SnapshotManifestResponse struct {
	ArtifactBytes           int64  `json:"artifact_bytes"`
	ArtifactObject          string `json:"artifact_object"`
	ArtifactSha256          string `json:"artifact_sha256"`
	ArtifactSignatureObject string `json:"artifact_signature_object"`

	// CreatedAtUnix Unix timestamp in seconds.
	CreatedAtUnix   UnixTimestamp `json:"created_at_unix"`
	EntryCount      int64         `json:"entry_count"`
	FormatVersion   int32         `json:"format_version"`
	ManifestVersion int32         `json:"manifest_version"`

	// MaxSeq Monotonic per-shard sequence number.
	MaxSeq     Sequence `json:"max_seq"`
	RuleCount  int64    `json:"rule_count"`
	ShardCount int32    `json:"shard_count"`
}

// SnapshotNameOrList defines model for SnapshotNameOrList.
type SnapshotNameOrList struct {
	union json.RawMessage
}

// SnapshotNameOrList0 defines model for .
type SnapshotNameOrList0 = string

// SnapshotNameOrList1 defines model for .
type SnapshotNameOrList1 = []string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// UnixTimestamp Unix timestamp in seconds.
type UnixTimestamp = int64

// WatermarksResponse defines model for WatermarksResponse.
type WatermarksResponse struct {
	ShardCount int32 `json:"shard_count"`
}

// DeliveryPriority defines model for DeliveryPriority.
type DeliveryPriority string

// FromSeq defines model for FromSeq.
type FromSeq = int64

// Key defines model for Key.
type Key = string

// Namespace defines model for Namespace.
type Namespace = string

// Shard defines model for Shard.
type Shard = int32

// SnapshotObject defines model for SnapshotObject.
type SnapshotObject = string

// TenantId defines model for TenantId.
type TenantId = string

// ToSeq defines model for ToSeq.
type ToSeq = int64

// Value defines model for Value.
type Value = string

// CommitOutcome defines model for CommitOutcome.
type CommitOutcome = CommitOutcomeResponse

// DecisionJson defines model for DecisionJson.
type DecisionJson = DecisionResponse

// ForbiddenJson defines model for ForbiddenJson.
type ForbiddenJson = ErrorResponse

// HistoryCompacted defines model for HistoryCompacted.
type HistoryCompacted = HistoryCompactedResponse

// RejectedJson defines model for RejectedJson.
type RejectedJson = ErrorResponse

// UnauthorizedJson defines model for UnauthorizedJson.
type UnauthorizedJson = ErrorResponse

// UnavailableJson defines model for UnavailableJson.
type UnavailableJson = ErrorResponse

// WatermarksJson defines model for WatermarksJson.
type WatermarksJson = WatermarksResponse

// Ack defines model for Ack.
type Ack = AckRequest

// DenyMutation defines model for DenyMutation.
type DenyMutation = DenyMutationRequest

// Rollback defines model for Rollback.
type Rollback = RollbackRequest

// RuleMutation defines model for RuleMutation.
type RuleMutation = RuleMutationRequest

// CheckAclDecisionParams defines parameters for CheckAclDecision.
type CheckAclDecisionParams struct {
	TenantId  TenantId  `form:"tenant_id" json:"tenant_id"`
	Namespace Namespace `form:"namespace" json:"namespace"`
	Value     Value     `form:"value" json:"value"`
}

// GetDeltaBundleParams defines parameters for GetDeltaBundle.
type GetDeltaBundleParams struct {
	Shard   Shard    `form:"shard" json:"shard"`
	FromSeq *FromSeq `form:"from_seq,omitempty" json:"from_seq,omitempty"`
	ToSeq   *ToSeq   `form:"to_seq,omitempty" json:"to_seq,omitempty"`
}

// GetDeltaBundleSignatureParams defines parameters for GetDeltaBundleSignature.
type GetDeltaBundleSignatureParams struct {
	Shard   Shard    `form:"shard" json:"shard"`
	FromSeq *FromSeq `form:"from_seq,omitempty" json:"from_seq,omitempty"`
	ToSeq   *ToSeq   `form:"to_seq,omitempty" json:"to_seq,omitempty"`
}

// LookupPointDecisionParams defines parameters for LookupPointDecision.
type LookupPointDecisionParams struct {
	TenantId  TenantId  `form:"tenant_id" json:"tenant_id"`
	Namespace Namespace `form:"namespace" json:"namespace"`
	Key       Key       `form:"key" json:"key"`
}

// GetMutationsParams defines parameters for GetMutations.
type GetMutationsParams struct {
	Shard            Shard                               `form:"shard" json:"shard"`
	FromSeq          *FromSeq                            `form:"from_seq,omitempty" json:"from_seq,omitempty"`
	DeliveryPriority *GetMutationsParamsDeliveryPriority `form:"delivery_priority,omitempty" json:"delivery_priority,omitempty"`
}

// GetMutationsParamsDeliveryPriority defines parameters for GetMutations.
type GetMutationsParamsDeliveryPriority string

// GetMutationsSignatureParams defines parameters for GetMutationsSignature.
type GetMutationsSignatureParams struct {
	Shard            Shard                                        `form:"shard" json:"shard"`
	FromSeq          *FromSeq                                     `form:"from_seq,omitempty" json:"from_seq,omitempty"`
	DeliveryPriority *GetMutationsSignatureParamsDeliveryPriority `form:"delivery_priority,omitempty" json:"delivery_priority,omitempty"`
}

// GetMutationsSignatureParamsDeliveryPriority defines parameters for GetMutationsSignature.
type GetMutationsSignatureParamsDeliveryPriority string

// GetSnapshotArtifactParams defines parameters for GetSnapshotArtifact.
type GetSnapshotArtifactParams struct {
	Object SnapshotObject `form:"object" json:"object"`
}

// GetSnapshotArtifactSignatureParams defines parameters for GetSnapshotArtifactSignature.
type GetSnapshotArtifactSignatureParams struct {
	Object SnapshotObject `form:"object" json:"object"`
}

// RecordAckJSONRequestBody defines body for RecordAck for application/json ContentType.
type RecordAckJSONRequestBody = AckRequest

// CreateDenyMutationJSONRequestBody defines body for CreateDenyMutation for application/json ContentType.
type CreateDenyMutationJSONRequestBody = DenyMutationRequest

// CreatePointMutationJSONRequestBody defines body for CreatePointMutation for application/json ContentType.
type CreatePointMutationJSONRequestBody = DenyMutationRequest

// RollbackToSnapshotJSONRequestBody defines body for RollbackToSnapshot for application/json ContentType.
type RollbackToSnapshotJSONRequestBody = RollbackRequest

// CreateRuleMutationJSONRequestBody defines body for CreateRuleMutation for application/json ContentType.
type CreateRuleMutationJSONRequestBody = RuleMutationRequest

// Getter for additional properties for AuditLogEntry. Returns the specified
// element and whether it was found
func (a AuditLogEntry) Get(fieldName string) (value AuditLogEntry_AdditionalProperties, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AuditLogEntry
func (a *AuditLogEntry) Set(fieldName string, value AuditLogEntry_AdditionalProperties) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]AuditLogEntry_AdditionalProperties)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AuditLogEntry to handle AdditionalProperties
func (a *AuditLogEntry) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["duplicate"]; found {
		err = json.Unmarshal(raw, &a.Duplicate)
		if err != nil {
			return fmt.Errorf("error reading 'duplicate': %w", err)
		}
		delete(object, "duplicate")
	}

	if raw, found := object["event"]; found {
		err = json.Unmarshal(raw, &a.Event)
		if err != nil {
			return fmt.Errorf("error reading 'event': %w", err)
		}
		delete(object, "event")
	}

	if raw, found := object["key"]; found {
		err = json.Unmarshal(raw, &a.Key)
		if err != nil {
			return fmt.Errorf("error reading 'key': %w", err)
		}
		delete(object, "key")
	}

	if raw, found := object["kind"]; found {
		err = json.Unmarshal(raw, &a.Kind)
		if err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["mutations"]; found {
		err = json.Unmarshal(raw, &a.Mutations)
		if err != nil {
			return fmt.Errorf("error reading 'mutations': %w", err)
		}
		delete(object, "mutations")
	}

	if raw, found := object["namespace"]; found {
		err = json.Unmarshal(raw, &a.Namespace)
		if err != nil {
			return fmt.Errorf("error reading 'namespace': %w", err)
		}
		delete(object, "namespace")
	}

	if raw, found := object["op_id"]; found {
		err = json.Unmarshal(raw, &a.OpId)
		if err != nil {
			return fmt.Errorf("error reading 'op_id': %w", err)
		}
		delete(object, "op_id")
	}

	if raw, found := object["pattern"]; found {
		err = json.Unmarshal(raw, &a.Pattern)
		if err != nil {
			return fmt.Errorf("error reading 'pattern': %w", err)
		}
		delete(object, "pattern")
	}

	if raw, found := object["reason"]; found {
		err = json.Unmarshal(raw, &a.Reason)
		if err != nil {
			return fmt.Errorf("error reading 'reason': %w", err)
		}
		delete(object, "reason")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["seq"]; found {
		err = json.Unmarshal(raw, &a.Seq)
		if err != nil {
			return fmt.Errorf("error reading 'seq': %w", err)
		}
		delete(object, "seq")
	}

	if raw, found := object["shard_id"]; found {
		err = json.Unmarshal(raw, &a.ShardId)
		if err != nil {
			return fmt.Errorf("error reading 'shard_id': %w", err)
		}
		delete(object, "shard_id")
	}

	if raw, found := object["snapshot"]; found {
		err = json.Unmarshal(raw, &a.Snapshot)
		if err != nil {
			return fmt.Errorf("error reading 'snapshot': %w", err)
		}
		delete(object, "snapshot")
	}

	if raw, found := object["ts"]; found {
		err = json.Unmarshal(raw, &a.Ts)
		if err != nil {
			return fmt.Errorf("error reading 'ts': %w", err)
		}
		delete(object, "ts")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]AuditLogEntry_AdditionalProperties)
		for fieldName, fieldBuf := range object {
			var fieldVal AuditLogEntry_AdditionalProperties
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AuditLogEntry to handle AdditionalProperties
func (a AuditLogEntry) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Duplicate != nil {
		object["duplicate"], err = json.Marshal(a.Duplicate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'duplicate': %w", err)
		}
	}

	object["event"], err = json.Marshal(a.Event)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event': %w", err)
	}

	if a.Key != nil {
		object["key"], err = json.Marshal(a.Key)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'key': %w", err)
		}
	}

	if a.Kind != nil {
		object["kind"], err = json.Marshal(a.Kind)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'kind': %w", err)
		}
	}

	if a.Mutations != nil {
		object["mutations"], err = json.Marshal(a.Mutations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mutations': %w", err)
		}
	}

	if a.Namespace != nil {
		object["namespace"], err = json.Marshal(a.Namespace)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'namespace': %w", err)
		}
	}

	if a.OpId != nil {
		object["op_id"], err = json.Marshal(a.OpId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'op_id': %w", err)
		}
	}

	if a.Pattern != nil {
		object["pattern"], err = json.Marshal(a.Pattern)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pattern': %w", err)
		}
	}

	if a.Reason != nil {
		object["reason"], err = json.Marshal(a.Reason)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reason': %w", err)
		}
	}

	object["result"], err = json.Marshal(a.Result)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'result': %w", err)
	}

	if a.Seq != nil {
		object["seq"], err = json.Marshal(a.Seq)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'seq': %w", err)
		}
	}

	if a.ShardId != nil {
		object["shard_id"], err = json.Marshal(a.ShardId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'shard_id': %w", err)
		}
	}

	if a.Snapshot != nil {
		object["snapshot"], err = json.Marshal(a.Snapshot)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'snapshot': %w", err)
		}
	}

	object["ts"], err = json.Marshal(a.Ts)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ts': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HealthResponse. Returns the specified
// element and whether it was found
func (a HealthResponse) Get(fieldName string) (value HealthResponse_AdditionalProperties, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HealthResponse
func (a *HealthResponse) Set(fieldName string, value HealthResponse_AdditionalProperties) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]HealthResponse_AdditionalProperties)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HealthResponse to handle AdditionalProperties
func (a *HealthResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["role"]; found {
		err = json.Unmarshal(raw, &a.Role)
		if err != nil {
			return fmt.Errorf("error reading 'role': %w", err)
		}
		delete(object, "role")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]HealthResponse_AdditionalProperties)
		for fieldName, fieldBuf := range object {
			var fieldVal HealthResponse_AdditionalProperties
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HealthResponse to handle AdditionalProperties
func (a HealthResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Role != nil {
		object["role"], err = json.Marshal(a.Role)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'role': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsPopAckRequest returns the union data inside the AckRequest as a PopAckRequest
func (t AckRequest) AsPopAckRequest() (PopAckRequest, error) {
	var body PopAckRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPopAckRequest overwrites any union data inside the AckRequest as the provided PopAckRequest
func (t *AckRequest) FromPopAckRequest(v PopAckRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePopAckRequest performs a merge with any union data inside the AckRequest, using the provided PopAckRequest
func (t *AckRequest) MergePopAckRequest(v PopAckRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPropagationAckRequest returns the union data inside the AckRequest as a PropagationAckRequest
func (t AckRequest) AsPropagationAckRequest() (PropagationAckRequest, error) {
	var body PropagationAckRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPropagationAckRequest overwrites any union data inside the AckRequest as the provided PropagationAckRequest
func (t *AckRequest) FromPropagationAckRequest(v PropagationAckRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePropagationAckRequest performs a merge with any union data inside the AckRequest, using the provided PropagationAckRequest
func (t *AckRequest) MergePropagationAckRequest(v PropagationAckRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AckRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AckRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAuditLogEntry0 returns the union data inside the AuditLogEntry_AdditionalProperties as a AuditLogEntry0
func (t AuditLogEntry_AdditionalProperties) AsAuditLogEntry0() (AuditLogEntry0, error) {
	var body AuditLogEntry0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAuditLogEntry0 overwrites any union data inside the AuditLogEntry_AdditionalProperties as the provided AuditLogEntry0
func (t *AuditLogEntry_AdditionalProperties) FromAuditLogEntry0(v AuditLogEntry0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAuditLogEntry0 performs a merge with any union data inside the AuditLogEntry_AdditionalProperties, using the provided AuditLogEntry0
func (t *AuditLogEntry_AdditionalProperties) MergeAuditLogEntry0(v AuditLogEntry0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAuditLogEntry1 returns the union data inside the AuditLogEntry_AdditionalProperties as a AuditLogEntry1
func (t AuditLogEntry_AdditionalProperties) AsAuditLogEntry1() (AuditLogEntry1, error) {
	var body AuditLogEntry1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAuditLogEntry1 overwrites any union data inside the AuditLogEntry_AdditionalProperties as the provided AuditLogEntry1
func (t *AuditLogEntry_AdditionalProperties) FromAuditLogEntry1(v AuditLogEntry1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAuditLogEntry1 performs a merge with any union data inside the AuditLogEntry_AdditionalProperties, using the provided AuditLogEntry1
func (t *AuditLogEntry_AdditionalProperties) MergeAuditLogEntry1(v AuditLogEntry1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAuditLogEntry2 returns the union data inside the AuditLogEntry_AdditionalProperties as a AuditLogEntry2
func (t AuditLogEntry_AdditionalProperties) AsAuditLogEntry2() (AuditLogEntry2, error) {
	var body AuditLogEntry2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAuditLogEntry2 overwrites any union data inside the AuditLogEntry_AdditionalProperties as the provided AuditLogEntry2
func (t *AuditLogEntry_AdditionalProperties) FromAuditLogEntry2(v AuditLogEntry2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAuditLogEntry2 performs a merge with any union data inside the AuditLogEntry_AdditionalProperties, using the provided AuditLogEntry2
func (t *AuditLogEntry_AdditionalProperties) MergeAuditLogEntry2(v AuditLogEntry2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AuditLogEntry_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AuditLogEntry_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAllowDecision returns the union data inside the DecisionResponse as a AllowDecision
func (t DecisionResponse) AsAllowDecision() (AllowDecision, error) {
	var body AllowDecision
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAllowDecision overwrites any union data inside the DecisionResponse as the provided AllowDecision
func (t *DecisionResponse) FromAllowDecision(v AllowDecision) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAllowDecision performs a merge with any union data inside the DecisionResponse, using the provided AllowDecision
func (t *DecisionResponse) MergeAllowDecision(v AllowDecision) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDenyDecision returns the union data inside the DecisionResponse as a DenyDecision
func (t DecisionResponse) AsDenyDecision() (DenyDecision, error) {
	var body DenyDecision
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDenyDecision overwrites any union data inside the DecisionResponse as the provided DenyDecision
func (t *DecisionResponse) FromDenyDecision(v DenyDecision) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDenyDecision performs a merge with any union data inside the DecisionResponse, using the provided DenyDecision
func (t *DecisionResponse) MergeDenyDecision(v DenyDecision) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DecisionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DecisionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsHealthResponse0 returns the union data inside the HealthResponse_AdditionalProperties as a HealthResponse0
func (t HealthResponse_AdditionalProperties) AsHealthResponse0() (HealthResponse0, error) {
	var body HealthResponse0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHealthResponse0 overwrites any union data inside the HealthResponse_AdditionalProperties as the provided HealthResponse0
func (t *HealthResponse_AdditionalProperties) FromHealthResponse0(v HealthResponse0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHealthResponse0 performs a merge with any union data inside the HealthResponse_AdditionalProperties, using the provided HealthResponse0
func (t *HealthResponse_AdditionalProperties) MergeHealthResponse0(v HealthResponse0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHealthResponse1 returns the union data inside the HealthResponse_AdditionalProperties as a HealthResponse1
func (t HealthResponse_AdditionalProperties) AsHealthResponse1() (HealthResponse1, error) {
	var body HealthResponse1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHealthResponse1 overwrites any union data inside the HealthResponse_AdditionalProperties as the provided HealthResponse1
func (t *HealthResponse_AdditionalProperties) FromHealthResponse1(v HealthResponse1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHealthResponse1 performs a merge with any union data inside the HealthResponse_AdditionalProperties, using the provided HealthResponse1
func (t *HealthResponse_AdditionalProperties) MergeHealthResponse1(v HealthResponse1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHealthResponse2 returns the union data inside the HealthResponse_AdditionalProperties as a HealthResponse2
func (t HealthResponse_AdditionalProperties) AsHealthResponse2() (HealthResponse2, error) {
	var body HealthResponse2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHealthResponse2 overwrites any union data inside the HealthResponse_AdditionalProperties as the provided HealthResponse2
func (t *HealthResponse_AdditionalProperties) FromHealthResponse2(v HealthResponse2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHealthResponse2 performs a merge with any union data inside the HealthResponse_AdditionalProperties, using the provided HealthResponse2
func (t *HealthResponse_AdditionalProperties) MergeHealthResponse2(v HealthResponse2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t HealthResponse_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *HealthResponse_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCanaryStatusResponse returns the union data inside the LatestCanaryResponse as a CanaryStatusResponse
func (t LatestCanaryResponse) AsCanaryStatusResponse() (CanaryStatusResponse, error) {
	var body CanaryStatusResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCanaryStatusResponse overwrites any union data inside the LatestCanaryResponse as the provided CanaryStatusResponse
func (t *LatestCanaryResponse) FromCanaryStatusResponse(v CanaryStatusResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCanaryStatusResponse performs a merge with any union data inside the LatestCanaryResponse, using the provided CanaryStatusResponse
func (t *LatestCanaryResponse) MergeCanaryStatusResponse(v CanaryStatusResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoCanaryStatus returns the union data inside the LatestCanaryResponse as a NoCanaryStatus
func (t LatestCanaryResponse) AsNoCanaryStatus() (NoCanaryStatus, error) {
	var body NoCanaryStatus
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoCanaryStatus overwrites any union data inside the LatestCanaryResponse as the provided NoCanaryStatus
func (t *LatestCanaryResponse) FromNoCanaryStatus(v NoCanaryStatus) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoCanaryStatus performs a merge with any union data inside the LatestCanaryResponse, using the provided NoCanaryStatus
func (t *LatestCanaryResponse) MergeNoCanaryStatus(v NoCanaryStatus) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LatestCanaryResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LatestCanaryResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSnapshotNameOrList0 returns the union data inside the SnapshotNameOrList as a SnapshotNameOrList0
func (t SnapshotNameOrList) AsSnapshotNameOrList0() (SnapshotNameOrList0, error) {
	var body SnapshotNameOrList0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSnapshotNameOrList0 overwrites any union data inside the SnapshotNameOrList as the provided SnapshotNameOrList0
func (t *SnapshotNameOrList) FromSnapshotNameOrList0(v SnapshotNameOrList0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSnapshotNameOrList0 performs a merge with any union data inside the SnapshotNameOrList, using the provided SnapshotNameOrList0
func (t *SnapshotNameOrList) MergeSnapshotNameOrList0(v SnapshotNameOrList0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSnapshotNameOrList1 returns the union data inside the SnapshotNameOrList as a SnapshotNameOrList1
func (t SnapshotNameOrList) AsSnapshotNameOrList1() (SnapshotNameOrList1, error) {
	var body SnapshotNameOrList1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSnapshotNameOrList1 overwrites any union data inside the SnapshotNameOrList as the provided SnapshotNameOrList1
func (t *SnapshotNameOrList) FromSnapshotNameOrList1(v SnapshotNameOrList1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSnapshotNameOrList1 performs a merge with any union data inside the SnapshotNameOrList, using the provided SnapshotNameOrList1
func (t *SnapshotNameOrList) MergeSnapshotNameOrList1(v SnapshotNameOrList1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SnapshotNameOrList) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SnapshotNameOrList) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
